// demos/vue/src/pages/fundamentals/controls/ToolbarUtilityPanelPage.vue
<script setup lang="ts">
import { KritzelEditor, KritzelWorkspace } from '@kritzel/vue-editor'
import { ref } from 'vue'
import { vueThemeDark } from '../../../const/vue-theme-dark'
import { vueThemeLight } from '../../../const/vue-theme-light'
import { createSeedObjects } from '../../getting-started/seed-objects'
import { editorStyle, hostStyle, toolbarStyle } from '../../shared/demo-shared'

const isToolbarVisible = ref(true)
const isUtilityPanelVisible = ref(true)
const themes = [vueThemeLight, vueThemeDark]
const workspaces = [new KritzelWorkspace({ objects: createSeedObjects() })]

function setToolbarVisible(event: Event) {
  isToolbarVisible.value = (event.target as HTMLInputElement).checked
}

function setUtilityPanelVisible(event: Event) {
  isUtilityPanelVisible.value = (event.target as HTMLInputElement).checked
}
</script>

<template>
  <div :style="hostStyle">
    <div :style="toolbarStyle">
      <label class="checkbox-control">
        <input type="checkbox" :checked="isToolbarVisible" @change="setToolbarVisible" />
        <span>Toolbar</span>
      </label>
      <label class="checkbox-control">
        <input type="checkbox" :checked="isUtilityPanelVisible" @change="setUtilityPanelVisible" />
        <span>Utility panel</span>
      </label>
    </div>
    <KritzelEditor
      editorId="toolbar-utility-panel"
      theme="light"
      :themes="themes"
      :workspaces="workspaces"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isToolbarVisible="isToolbarVisible"
      :isUtilityPanelVisible="isUtilityPanelVisible"
      :style="editorStyle"
    />
  </div>
</template>

<style scoped>
.checkbox-control {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  color: #333;
  font-size: 13px;
  cursor: pointer;
}
</style>

// demos/react/src/pages/fundamentals/controls/ToolbarUtilityPanelPage.tsx
import { useState } from "react";
import { KritzelEditor, KritzelWorkspace } from "@kritzel/react-editor";
import { reactThemeDark } from "../../../const/react-theme-dark";
import { reactThemeLight } from "../../../const/react-theme-light";
import { createSeedObjects } from "../../getting-started/seed-objects";
import { editorStyle, hostStyle, toolbarStyle } from "../../shared/demo-shared";

const themes = [reactThemeLight, reactThemeDark];

export function ToolbarUtilityPanelPage() {
  const [isToolbarVisible, setIsToolbarVisible] = useState(true);
  const [isUtilityPanelVisible, setIsUtilityPanelVisible] = useState(true);
  const [workspaces] = useState(() => [
    new KritzelWorkspace({ objects: createSeedObjects() }),
  ]);

  return (
    <div style={hostStyle}>
      <div style={toolbarStyle}>
        <label style={{ display: "inline-flex", alignItems: "center", gap: "8px", fontSize: "13px", color: "#333", cursor: "pointer" }}>
          <input
            type="checkbox"
            checked={isToolbarVisible}
            onChange={(event) => setIsToolbarVisible(event.currentTarget.checked)}
          />
          <span>Toolbar</span>
        </label>
        <label style={{ display: "inline-flex", alignItems: "center", gap: "8px", fontSize: "13px", color: "#333", cursor: "pointer" }}>
          <input
            type="checkbox"
            checked={isUtilityPanelVisible}
            onChange={(event) => setIsUtilityPanelVisible(event.currentTarget.checked)}
          />
          <span>Utility panel</span>
        </label>
      </div>
      <KritzelEditor
        editorId="toolbar-utility-panel"
        theme="light"
        themes={themes}
        workspaces={workspaces}
        syncConfig={undefined}
        loginConfig={undefined}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isToolbarVisible={isToolbarVisible}
        isUtilityPanelVisible={isUtilityPanelVisible}
        style={editorStyle}
      />
    </div>
  );
}
