// demos/vue/src/pages/DemoIndexPage.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { RouterLink } from 'vue-router'
import { demoCategories, demoRoutes, type DemoCategory } from '../demo-routes'

const query = ref('')
const visibleRoutes = demoRoutes.filter((route) => !route.hidden)
const collapsedCategories = ref<Set<DemoCategory['id']>>(
  new Set(demoCategories.map((category) => category.id)),
)

const filteredCategories = computed(() => {
  const terms = query.value.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean)

  return demoCategories
    .map((category) => ({
      ...category,
      routes: visibleRoutes.filter((route) => {
        if (route.category !== category.id) return false
        if (terms.length === 0) return true

        const searchableText = `${category.title} ${route.title} ${route.context ?? ''} ${route.path}`.toLocaleLowerCase()
        return terms.every((term) => searchableText.includes(term))
      }),
    }))
    .filter((category) => category.routes.length > 0)
})

const visibleDemoCount = computed(() =>
  filteredCategories.value.reduce((count, category) => count + category.routes.length, 0),
)

watch(query, (value) => {
  if (!value.trim()) {
    collapsedCategories.value = new Set(demoCategories.map((category) => category.id))
    return
  }

  const matchingCategories = new Set(filteredCategories.value.map((category) => category.id))
  collapsedCategories.value = new Set(
    [...collapsedCategories.value].filter((category) => !matchingCategories.has(category)),
  )
})

function isCollapsed(category: DemoCategory['id']): boolean {
  return collapsedCategories.value.has(category)
}

function toggleCategory(category: DemoCategory['id']): void {
  const updatedCategories = new Set(collapsedCategories.value)
  if (updatedCategories.has(category)) {
    updatedCategories.delete(category)
  } else {
    updatedCategories.add(category)
  }
  collapsedCategories.value = updatedCategories
}
</script>

<template>
  <div class="demo-index">
    <header>
      <h1>Demo directory</h1>
      <p class="summary" aria-live="polite">
        {{ visibleDemoCount }} of {{ visibleRoutes.length }} routes
      </p>
      <label for="demo-search">Search demos</label>
      <input
        id="demo-search"
        v-model="query"
        type="search"
        placeholder="Search by name, category, or path"
        autocomplete="off"
      />
    </header>

    <main>
      <section v-for="category in filteredCategories" :key="category.id">
        <h2>
          <button
            type="button"
            :aria-expanded="!isCollapsed(category.id)"
            :aria-controls="`${category.id}-demos`"
            @click="toggleCategory(category.id)"
          >
            <span class="chevron" :class="{ collapsed: isCollapsed(category.id) }" aria-hidden="true" />
            <span>{{ category.title }}</span>
            <span class="category-count">{{ category.routes.length }}</span>
          </button>
        </h2>
        <nav
          :id="`${category.id}-demos`"
          :aria-label="`${category.title} demos`"
          :hidden="isCollapsed(category.id)"
        >
          <RouterLink v-for="route in category.routes" :key="route.path" :to="route.path">
            <span class="link-copy">
              <strong>{{ route.title }}</strong>
              <small v-if="route.context">{{ route.context }}</small>
            </span>
          </RouterLink>
        </nav>
      </section>

      <p v-if="filteredCategories.length === 0" class="empty-state">
        No demos match "{{ query }}".
      </p>
    </main>
  </div>
</template>

<style scoped>
.demo-index {
  min-height: 100dvh;
  box-sizing: border-box;
  overflow-y: auto;
  color: #202124;
  background: #ffffff;
  font-family: Avenir, Montserrat, Corbel, sans-serif;
}

header {
  max-width: 800px;
  margin: 0 auto;
  padding: 32px 24px 24px;
  box-sizing: border-box;
  border-bottom: 1px solid #e5e5e5;
}

h1 {
  margin: 0;
  font-size: 28px;
  line-height: 1.2;
  letter-spacing: 0;
}

.summary {
  margin: 6px 0 0;
  color: #666666;
  font-size: 14px;
}

label {
  display: block;
  margin-top: 24px;
  margin-bottom: 6px;
  font-size: 13px;
  font-weight: 600;
}

input {
  width: min(100%, 560px);
  height: 40px;
  padding: 0 12px;
  box-sizing: border-box;
  color: inherit;
  background: #ffffff;
  border: 1px solid #b8b8b8;
  border-radius: 4px;
  font: inherit;
  font-size: 14px;
}

input:focus {
  border-color: #087f5b;
  outline: 2px solid rgb(8 127 91 / 18%);
}

main {
  display: grid;
  grid-template-columns: minmax(0, 1fr);
  gap: 12px;
  max-width: 800px;
  margin: 0 auto;
  padding: 32px 24px 64px;
  box-sizing: border-box;
}

section {
  min-width: 0;
}

h2 {
  margin: 0;
  letter-spacing: 0;
  border-bottom: 1px solid #cfcfcf;
}

h2 button {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  padding: 8px 4px;
  color: inherit;
  background: transparent;
  border: 0;
  cursor: pointer;
  font: inherit;
  font-size: 16px;
  font-weight: 650;
  text-align: left;
}

h2 button:hover,
h2 button:focus-visible,
a:hover,
a:focus-visible {
  color: #087f5b;
  background: #f6faf8;
  outline: none;
}

h2 button:focus-visible,
a:focus-visible {
  box-shadow: inset 3px 0 #0ca678;
}

.chevron {
  width: 8px;
  height: 8px;
  border-right: 2px solid currentColor;
  border-bottom: 2px solid currentColor;
  transform: rotate(45deg);
  transition: transform 120ms ease;
}

.chevron.collapsed {
  transform: rotate(-45deg);
}

.category-count {
  margin-left: auto;
  color: #666666;
  font-size: 13px;
  font-weight: 400;
  font-variant-numeric: tabular-nums;
}

nav {
  display: grid;
}

nav[hidden] {
  display: none;
}

a {
  display: flex;
  align-items: center;
  min-height: 48px;
  padding: 8px 4px;
  box-sizing: border-box;
  color: inherit;
  text-decoration: none;
  border-bottom: 1px solid #eeeeee;
}

.link-copy {
  display: grid;
  gap: 4px;
  min-width: 0;
}

strong {
  overflow-wrap: anywhere;
  font-size: 14px;
  font-weight: 600;
}

small {
  color: #666666;
  font-size: 12px;
}

.empty-state {
  margin: 0;
  color: #666666;
  font-size: 14px;
}

@media (max-width: 600px) {
  header {
    padding-top: 24px;
  }

  main {
    padding-top: 24px;
  }
}
</style>

// demos/react/src/pages/DemoIndexPage.tsx
import { useState, type CSSProperties } from "react";
import { Link } from "react-router-dom";
import { demoRoutes, type DemoRoute } from "../demo-routes";

interface DemoCategory {
  title: string;
  links: readonly DemoRoute[];
}

const categories = createCategories(demoRoutes.filter((route) => route.isIndexed !== false));
const demoCount = categories.reduce((count, category) => count + category.links.length, 0);

export function DemoIndexPage() {
  const [query, setQuery] = useState("");
  const [collapsedCategories, setCollapsedCategories] = useState<ReadonlySet<string>>(
    () => new Set(categories.map((category) => category.title)),
  );
  const terms = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
  const filteredCategories = terms.length === 0
    ? categories
    : categories
      .map((category) => ({
        ...category,
        links: category.links.filter((link) => {
          const searchableText = `${category.title} ${link.title} ${link.context ?? ""} ${link.path}`.toLocaleLowerCase();
          return terms.every((term) => searchableText.includes(term));
        }),
      }))
      .filter((category) => category.links.length > 0);
  const visibleDemoCount = filteredCategories.reduce((count, category) => count + category.links.length, 0);

  function updateQuery(value: string) {
    setQuery(value);
    if (!value.trim()) {
      setCollapsedCategories(new Set(categories.map((category) => category.title)));
      return;
    }

    setCollapsedCategories(new Set());
  }

  function toggleCategory(category: string) {
    setCollapsedCategories((current) => {
      const updated = new Set(current);
      if (updated.has(category)) {
        updated.delete(category);
      } else {
        updated.add(category);
      }
      return updated;
    });
  }

  return (
    <div style={pageStyle}>
      <header style={headerStyle}>
        <h1 style={headingStyle}>Demo directory</h1>
        <p style={summaryStyle}>{visibleDemoCount} of {demoCount} routes</p>
        <label htmlFor="demo-search" style={labelStyle}>Search demos</label>
        <input
          id="demo-search"
          type="search"
          placeholder="Search by name, category, or path"
          autoComplete="off"
          value={query}
          onChange={(event) => updateQuery(event.currentTarget.value)}
          style={inputStyle}
        />
      </header>

      <main style={mainStyle}>
        {filteredCategories.map((category) => {
          const isCollapsed = collapsedCategories.has(category.title);
          const categoryId = `${category.title.toLocaleLowerCase().replace(/\s+/g, "-")}-demos`;

          return (
            <section key={category.title}>
              <h2 style={categoryHeadingStyle}>
                <button
                  type="button"
                  aria-expanded={!isCollapsed}
                  aria-controls={categoryId}
                  onClick={() => toggleCategory(category.title)}
                  style={categoryButtonStyle}
                >
                  <span aria-hidden="true" style={{ ...chevronStyle, transform: isCollapsed ? "rotate(0deg)" : "rotate(90deg)" }}>&gt;</span>
                  <span>{category.title}</span>
                  <span style={categoryCountStyle}>{category.links.length}</span>
                </button>
              </h2>
              {!isCollapsed && (
                <nav id={categoryId} aria-label={`${category.title} demos`} style={navStyle}>
                  {category.links.map((link) => (
                    <Link key={link.path} to={link.path} style={linkStyle}>
                      <span style={linkCopyStyle}>
                        <strong style={linkTitleStyle}>{link.title}</strong>
                        {link.context && <small style={contextStyle}>{link.context}</small>}
                      </span>
                    </Link>
                  ))}
                </nav>
              )}
            </section>
          );
        })}
        {filteredCategories.length === 0 && <p style={summaryStyle}>No demos match &quot;{query}&quot;.</p>}
      </main>
    </div>
  );
}

function createCategories(routes: readonly DemoRoute[]): DemoCategory[] {
  const groupedRoutes = new Map<string, DemoRoute[]>();
  for (const route of routes) {
    const categoryRoutes = groupedRoutes.get(route.category) ?? [];
    categoryRoutes.push(route);
    groupedRoutes.set(route.category, categoryRoutes);
  }

  return [...groupedRoutes].map(([title, links]) => ({ title, links }));
}

const pageStyle: CSSProperties = { height: "100dvh", overflowY: "auto", color: "#202124", background: "#ffffff", fontFamily: "Roboto, sans-serif" };
const headerStyle: CSSProperties = { maxWidth: "800px", margin: "0 auto", padding: "32px 24px 24px", boxSizing: "border-box", borderBottom: "1px solid #e5e5e5" };
const headingStyle: CSSProperties = { margin: 0, fontSize: "28px", lineHeight: 1.2, letterSpacing: 0 };
const summaryStyle: CSSProperties = { margin: "6px 0 0", color: "#666666", fontSize: "14px" };
const labelStyle: CSSProperties = { display: "block", marginTop: "24px", marginBottom: "6px", fontSize: "13px", fontWeight: 500 };
const inputStyle: CSSProperties = { width: "min(100%, 560px)", height: "40px", padding: "0 12px", boxSizing: "border-box", color: "inherit", background: "#ffffff", border: "1px solid #c7c7c7", borderRadius: "4px", font: "inherit", fontSize: "14px" };
const mainStyle: CSSProperties = { display: "grid", gridTemplateColumns: "minmax(0, 1fr)", gap: "12px", maxWidth: "800px", margin: "0 auto", padding: "32px 24px 64px", boxSizing: "border-box" };
const categoryHeadingStyle: CSSProperties = { margin: 0, letterSpacing: 0, borderBottom: "1px solid #cfcfcf" };
const categoryButtonStyle: CSSProperties = { display: "flex", alignItems: "center", gap: "8px", width: "100%", padding: "8px 4px", color: "inherit", background: "transparent", border: 0, cursor: "pointer", font: "inherit", fontSize: "16px", fontWeight: 600, textAlign: "left" };
const chevronStyle: CSSProperties = { width: "16px", textAlign: "center", transition: "transform 120ms ease" };
const categoryCountStyle: CSSProperties = { marginLeft: "auto", color: "#777777", fontSize: "13px", fontWeight: 400, fontVariantNumeric: "tabular-nums" };
const navStyle: CSSProperties = { display: "grid" };
const linkStyle: CSSProperties = { display: "flex", alignItems: "center", minHeight: "48px", padding: "8px 4px", boxSizing: "border-box", color: "inherit", textDecoration: "none", borderBottom: "1px solid #eeeeee" };
const linkCopyStyle: CSSProperties = { display: "grid", gap: "4px", minWidth: 0 };
const linkTitleStyle: CSSProperties = { overflowWrap: "anywhere", fontSize: "14px", fontWeight: 500 };
const contextStyle: CSSProperties = { color: "#777777", fontSize: "12px" };
