// demos/react/src/pages/fundamentals/viewport/ViewportEventsPage.tsx
import { useRef, useState } from "react";
import {
  KritzelEditor,
  type HTMLKritzelEditorElement,
  type KritzelViewportState,
} from "@kritzel/react-editor";
import { reactThemeDark } from "../../../const/react-theme-dark";
import { reactThemeLight } from "../../../const/react-theme-light";
import { editorStyle, hostStyle, seedEditor } from "../../shared/demo-shared";
import { Toolbar } from "../../../components/Toolbar";

const themes = [reactThemeLight, reactThemeDark];
const panStep = 100;
const zoomFactor = 1.1;

export function ViewportEventsPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const [viewport, setViewport] = useState<KritzelViewportState | null>(null);

  async function panBy(offsetX: number, offsetY: number) {
    const editor = editorRef.current;
    if (!editor) {
      return;
    }

    const currentViewport = await editor.getViewport();
    const centerWorldX = (currentViewport.width / 2 - currentViewport.translateX) / currentViewport.scale;
    const centerWorldY = (currentViewport.height / 2 - currentViewport.translateY) / currentViewport.scale;
    await editor.setViewport(
      centerWorldX + offsetX,
      centerWorldY + offsetY,
      currentViewport.scale,
    );
  }

  function onViewportChange(event: CustomEvent<KritzelViewportState>) {
    setViewport(event.detail);
  }

  return (
    <div style={hostStyle}>
      <Toolbar>
        <button onClick={() => void panBy(0, -panStep)}>Pan Up</button>
        <button onClick={() => void panBy(0, panStep)}>Pan Down</button>
        <button onClick={() => void panBy(-panStep, 0)}>Pan Left</button>
        <button onClick={() => void panBy(panStep, 0)}>Pan Right</button>
        <button onClick={() => void editorRef.current?.zoomIn(zoomFactor, 200)}>Zoom In</button>
        <button onClick={() => void editorRef.current?.zoomOut(zoomFactor, 200)}>Zoom Out</button>
        <span className="status">X: {Math.round(viewport?.translateX ?? 0)}</span>
        <span className="status">Y: {Math.round(viewport?.translateY ?? 0)}</span>
        <span className="status">Scale: {(viewport?.scale ?? 1).toFixed(2)}</span>
      </Toolbar>
      <KritzelEditor
        ref={editorRef}
        editorId="viewport-events"
        theme="light"
        themes={themes}
        syncConfig={undefined}
        loginConfig={undefined}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        onIsReady={() => {
          if (editorRef.current) {
            void seedEditor(editorRef.current);
          }
        }}
        onViewportChange={onViewportChange}
        style={editorStyle}
      />
    </div>
  );
}

// demos/vue/src/pages/fundamentals/viewport/ViewportEventsPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import {
  getEditorRef,
  KritzelEditor,
  KritzelWorkspace,
  type KritzelViewportState,
} from '@kritzel/vue-editor'
import { vueThemeDark } from '../../../const/vue-theme-dark'
import { vueThemeLight } from '../../../const/vue-theme-light'
import { createSeedObjects } from '../../getting-started/seed-objects'
import { editorStyle, hostStyle } from '../../shared/demo-shared'
import Toolbar from '../../../components/Toolbar.vue'

const panStep = 100
const zoomFactor = 1.1
const themes = [vueThemeLight, vueThemeDark]
const workspaces = [new KritzelWorkspace({ objects: createSeedObjects() })]
const editor = getEditorRef('editor')
const viewport = ref<KritzelViewportState | null>(null)

async function panBy(offsetX: number, offsetY: number) {
  if (!editor.value) {
    return
  }

  const currentViewport = await editor.value.getViewport()
  const centerWorldX = (currentViewport.width / 2 - currentViewport.translateX) / currentViewport.scale
  const centerWorldY = (currentViewport.height / 2 - currentViewport.translateY) / currentViewport.scale
  await editor.value.setViewport(
    centerWorldX + offsetX,
    centerWorldY + offsetY,
    currentViewport.scale,
  )
}

async function panUp() {
  await panBy(0, -panStep)
}

async function panDown() {
  await panBy(0, panStep)
}

async function panLeft() {
  await panBy(-panStep, 0)
}

async function panRight() {
  await panBy(panStep, 0)
}

async function zoomIn() {
  await editor.value?.zoomIn(zoomFactor, 200)
}

async function zoomOut() {
  await editor.value?.zoomOut(zoomFactor, 200)
}

function onViewportChange(event: Event) {
  viewport.value = (event as CustomEvent<KritzelViewportState>).detail
}
</script>

<template>
  <div :style="hostStyle">
    <Toolbar>
      <button @click="panUp">Pan Up</button>
      <button @click="panDown">Pan Down</button>
      <button @click="panLeft">Pan Left</button>
      <button @click="panRight">Pan Right</button>
      <button @click="zoomIn">Zoom In</button>
      <button @click="zoomOut">Zoom Out</button>
      <span>X: {{ Math.round(viewport?.translateX ?? 0) }}</span>
      <span>Y: {{ Math.round(viewport?.translateY ?? 0) }}</span>
      <span>Scale: {{ (viewport?.scale ?? 1).toFixed(2) }}</span>
    </Toolbar>
    <KritzelEditor
      ref="editor"
      editorId="viewport-events"
      theme="light"
      :themes="themes"
      :workspaces="workspaces"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isMoreMenuVisible="false"
      :isWorkspaceManagerVisible="false"
      :style="editorStyle"
      @viewportChange="onViewportChange"
    />
  </div>
</template>
