// demos/vue/src/pages/fundamentals/objects/ObjectsRemovePage.vue
<script setup lang="ts">
import {
  getEditorRef,
  KritzelEditor,
  KritzelWorkspace,
  type KritzelBaseObject,
} from '@kritzel/vue-editor'
import { ref } from 'vue'
import { vueThemeDark } from '../../../const/vue-theme-dark'
import { vueThemeLight } from '../../../const/vue-theme-light'
import { createSeedObjects } from '../../getting-started/seed-objects'
import { buttonStyle, editorStyle, hostStyle, toolbarStyle } from '../../shared/demo-shared'

const editor = getEditorRef('editor')
const seedObjects = createSeedObjects()
const objects = ref<KritzelBaseObject[]>(seedObjects)
const themes = [vueThemeLight, vueThemeDark]
const workspaces = [new KritzelWorkspace({ objects: seedObjects })]

async function removeLastObject() {
  const all = (await editor.value?.getAllObjects()) ?? []
  const lastObject = all.at(-1)
  if (!lastObject) {
    return
  }

  await editor.value?.removeObject(lastObject)
  objects.value = (await editor.value?.getAllObjects()) ?? []
}
</script>

<template>
  <div :style="hostStyle">
    <div :style="toolbarStyle">
      <button :style="buttonStyle()" :disabled="objects.length === 0" @click="removeLastObject">
        Remove Object
      </button>
    </div>
    <KritzelEditor
      ref="editor"
      editorId="objects-remove"
      theme="light"
      :themes="themes"
      :workspaces="workspaces"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isMoreMenuVisible="false"
      :isWorkspaceManagerVisible="false"
      :style="editorStyle"
    />
  </div>
</template>

// demos/react/src/pages/fundamentals/objects/ObjectsRemovePage.tsx
import { useRef, useState } from "react";
import {
  HTMLKritzelEditorElement,
  KritzelEditor,
  KritzelWorkspace,
  type KritzelBaseObject,
} from "@kritzel/react-editor";
import { reactThemeDark } from "../../../const/react-theme-dark";
import { reactThemeLight } from "../../../const/react-theme-light";
import { createSeedObjects } from "../../getting-started/seed-objects";
import { buttonStyle, editorStyle, hostStyle, toolbarStyle } from "../../shared/demo-shared";

const themes = [reactThemeLight, reactThemeDark];

export function ObjectsRemovePage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const [seedObjects] = useState<KritzelBaseObject[]>(createSeedObjects);
  const [objects, setObjects] = useState(seedObjects);
  const [workspaces] = useState(() => [new KritzelWorkspace({ objects: seedObjects })]);

  async function removeLastObject() {
    const editor = editorRef.current;
    if (!editor) return;
    const all = await editor.getAllObjects();
    const lastObject = all.at(-1);
    if (!lastObject) return;
    await editor.removeObject(lastObject);
    setObjects(await editor.getAllObjects());
  }

  return (
    <div style={hostStyle}>
      <div style={toolbarStyle}>
        <button
          style={buttonStyle(false)}
          onClick={() => void removeLastObject()}
          disabled={objects.length === 0}
        >
          Remove Object
        </button>
      </div>
      <KritzelEditor
        ref={editorRef}
        editorId="objects-remove"
        theme="light"
        themes={themes}
        workspaces={workspaces}
        syncConfig={undefined}
        loginConfig={undefined}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        style={editorStyle}
      />
    </div>
  );
}
