// demos/vue/src/pages/fundamentals/viewport/ViewportBoundariesPage.vue
<script setup lang="ts">
import { getEditorRef, KritzelEditor, KritzelWorkspace } from '@kritzel/vue-editor'
import { vueThemeDark } from '../../../const/vue-theme-dark'
import { vueThemeLight } from '../../../const/vue-theme-light'
import { createSeedObjects } from '../../getting-started/seed-objects'
import { editorStyle, hostStyle } from '../../shared/demo-shared'
import Toolbar from '../../../components/Toolbar.vue'

const panStep = 100
const themes = [vueThemeLight, vueThemeDark]
const workspaces = [new KritzelWorkspace({ objects: createSeedObjects() })]
const editor = getEditorRef('editor')

async function panBy(offsetX: number, offsetY: number) {
  if (!editor.value) {
    return
  }

  const currentViewport = await editor.value.getViewport()
  const centerWorldX = (currentViewport.width / 2 - currentViewport.translateX) / currentViewport.scale
  const centerWorldY = (currentViewport.height / 2 - currentViewport.translateY) / currentViewport.scale
  await editor.value.setViewport(
    centerWorldX + offsetX,
    centerWorldY + offsetY,
    currentViewport.scale,
  )
}

async function panUp() {
  await panBy(0, -panStep)
}

async function panDown() {
  await panBy(0, panStep)
}

async function panLeft() {
  await panBy(-panStep, 0)
}

async function panRight() {
  await panBy(panStep, 0)
}
</script>

<template>
  <div :style="hostStyle">
    <Toolbar>
      <button @click="panUp">Pan Up</button>
      <button @click="panDown">Pan Down</button>
      <button @click="panLeft">Pan Left</button>
      <button @click="panRight">Pan Right</button>
    </Toolbar>
    <KritzelEditor
      ref="editor"
      editorId="viewport-boundaries"
      theme="light"
      :themes="themes"
      :workspaces="workspaces"
      :viewportBoundaryLeft="-500"
      :viewportBoundaryRight="500"
      :viewportBoundaryTop="-400"
      :viewportBoundaryBottom="400"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isMoreMenuVisible="false"
      :isWorkspaceManagerVisible="false"
      :style="editorStyle"
    />
  </div>
</template>

// demos/react/src/pages/fundamentals/viewport/ViewportBoundariesPage.tsx
import { useRef } from "react";
import { KritzelEditor, type HTMLKritzelEditorElement } from "@kritzel/react-editor";
import { reactThemeDark } from "../../../const/react-theme-dark";
import { reactThemeLight } from "../../../const/react-theme-light";
import { editorStyle, hostStyle, seedEditor } from "../../shared/demo-shared";
import { Toolbar } from "../../../components/Toolbar";

const themes = [reactThemeLight, reactThemeDark];
const panStep = 100;

export function ViewportBoundariesPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);

  async function panBy(offsetX: number, offsetY: number) {
    const editor = editorRef.current;
    if (!editor) {
      return;
    }

    const currentViewport = await editor.getViewport();
    const centerWorldX = (currentViewport.width / 2 - currentViewport.translateX) / currentViewport.scale;
    const centerWorldY = (currentViewport.height / 2 - currentViewport.translateY) / currentViewport.scale;
    await editor.setViewport(
      centerWorldX + offsetX,
      centerWorldY + offsetY,
      currentViewport.scale,
    );
  }

  return (
    <div style={hostStyle}>
      <Toolbar>
        <button onClick={() => void panBy(0, -panStep)}>Pan Up</button>
        <button onClick={() => void panBy(0, panStep)}>Pan Down</button>
        <button onClick={() => void panBy(-panStep, 0)}>Pan Left</button>
        <button onClick={() => void panBy(panStep, 0)}>Pan Right</button>
      </Toolbar>
      <KritzelEditor
        ref={editorRef}
        editorId="viewport-boundaries"
        theme="light"
        themes={themes}
        syncConfig={undefined}
        loginConfig={undefined}
        viewportBoundaryLeft={-500}
        viewportBoundaryRight={500}
        viewportBoundaryTop={-400}
        viewportBoundaryBottom={400}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        onIsReady={() => {
          if (editorRef.current) {
            void seedEditor(editorRef.current);
          }
        }}
        style={editorStyle}
      />
    </div>
  );
}
