// demos/react/src/pages/fundamentals/controls/WorkspaceManagerOpenPage.tsx
import { useRef, useState } from "react";
import {
  HTMLKritzelEditorElement,
  InMemorySyncProvider,
  KritzelEditor,
  KritzelWorkspace,
  type KritzelSyncConfig,
} from "@kritzel/react-editor";
import { reactThemeDark } from "../../../const/react-theme-dark";
import { reactThemeLight } from "../../../const/react-theme-light";
import { createSeedObjects } from "../../getting-started/seed-objects";
import { editorStyle, hostStyle, toolbarStyle } from "../../shared/demo-shared";

const themes = [reactThemeLight, reactThemeDark];
const syncConfig: KritzelSyncConfig = { providers: [InMemorySyncProvider] };

export function WorkspaceManagerOpenPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const [isWorkspaceManagerVisible, setIsWorkspaceManagerVisible] = useState(true);
  const [workspaces] = useState(() => [
    new KritzelWorkspace({ objects: createSeedObjects() }),
  ]);

  async function onReady() {
    await editorRef.current?.openWorkspaceManagerMenu();
  }

  return (
    <div style={hostStyle}>
      <div style={toolbarStyle}>
        <label style={{ display: "inline-flex", alignItems: "center", gap: "8px", fontSize: "13px", color: "#333", cursor: "pointer" }}>
          <input
            type="checkbox"
            checked={isWorkspaceManagerVisible}
            onChange={(event) => setIsWorkspaceManagerVisible(event.currentTarget.checked)}
          />
          <span>Workspace manager</span>
        </label>
      </div>
      <KritzelEditor
        ref={editorRef}
        editorId="workspace-manager-open"
        theme="light"
        themes={themes}
        workspaces={workspaces}
        syncConfig={syncConfig}
        loginConfig={undefined}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isWorkspaceManagerVisible={isWorkspaceManagerVisible}
        onIsReady={() => void onReady()}
        style={editorStyle}
      />
    </div>
  );
}

// demos/vue/src/pages/fundamentals/controls/WorkspaceManagerOpenPage.vue
<script setup lang="ts">
import {
  getEditorRef,
  InMemorySyncProvider,
  KritzelEditor,
  KritzelWorkspace,
  type KritzelSyncConfig,
} from '@kritzel/vue-editor'
import { ref } from 'vue'
import { vueThemeDark } from '../../../const/vue-theme-dark'
import { vueThemeLight } from '../../../const/vue-theme-light'
import { createSeedObjects } from '../../getting-started/seed-objects'
import { editorStyle, hostStyle, toolbarStyle } from '../../shared/demo-shared'

const editor = getEditorRef('editor')
const isWorkspaceManagerVisible = ref(true)
const themes = [vueThemeLight, vueThemeDark]
const workspaces = [new KritzelWorkspace({ objects: createSeedObjects() })]
const syncConfig: KritzelSyncConfig = { providers: [InMemorySyncProvider] }

async function onReady() {
  await editor.value?.openWorkspaceManagerMenu()
}

function setWorkspaceManagerVisible(event: Event) {
  isWorkspaceManagerVisible.value = (event.target as HTMLInputElement).checked
}
</script>

<template>
  <div :style="hostStyle">
    <div :style="toolbarStyle">
      <label class="checkbox-control">
        <input
          type="checkbox"
          :checked="isWorkspaceManagerVisible"
          @change="setWorkspaceManagerVisible"
        />
        <span>Workspace manager</span>
      </label>
    </div>
    <KritzelEditor
      ref="editor"
      editorId="workspace-manager-open"
      theme="light"
      :themes="themes"
      :workspaces="workspaces"
      :syncConfig="syncConfig"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isWorkspaceManagerVisible="isWorkspaceManagerVisible"
      :style="editorStyle"
      @isReady="onReady"
    />
  </div>
</template>

<style scoped>
.checkbox-control {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  color: #333;
  font-size: 13px;
  cursor: pointer;
}
</style>
