// demos/react/src/pages/fundamentals/controls/ZoomPanelTogglePage.tsx
import { useState } from "react";
import { KritzelEditor, KritzelWorkspace } from "@kritzel/react-editor";
import { reactThemeDark } from "../../../const/react-theme-dark";
import { reactThemeLight } from "../../../const/react-theme-light";
import { createSeedObjects } from "../../getting-started/seed-objects";
import { editorStyle, hostStyle, toolbarStyle } from "../../shared/demo-shared";

const themes = [reactThemeLight, reactThemeDark];

export function ZoomPanelTogglePage() {
  const [isZoomPanelVisible, setIsZoomPanelVisible] = useState(true);
  const [workspaces] = useState(() => [
    new KritzelWorkspace({ objects: createSeedObjects() }),
  ]);

  return (
    <div style={hostStyle}>
      <div style={toolbarStyle}>
        <label style={{ display: "inline-flex", alignItems: "center", gap: "8px", fontSize: "13px", color: "#333", cursor: "pointer" }}>
          <input
            type="checkbox"
            checked={isZoomPanelVisible}
            onChange={(event) => setIsZoomPanelVisible(event.currentTarget.checked)}
          />
          <span>Zoom panel</span>
        </label>
      </div>
      <KritzelEditor
        editorId="zoom-panel-toggle"
        theme="light"
        themes={themes}
        workspaces={workspaces}
        syncConfig={undefined}
        loginConfig={undefined}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isZoomPanelVisible={isZoomPanelVisible}
        style={editorStyle}
      />
    </div>
  );
}

// demos/vue/src/pages/fundamentals/controls/ZoomPanelTogglePage.vue
<script setup lang="ts">
import { KritzelEditor, KritzelWorkspace } from '@kritzel/vue-editor'
import { ref } from 'vue'
import { vueThemeDark } from '../../../const/vue-theme-dark'
import { vueThemeLight } from '../../../const/vue-theme-light'
import { createSeedObjects } from '../../getting-started/seed-objects'
import { editorStyle, hostStyle, toolbarStyle } from '../../shared/demo-shared'

const isZoomPanelVisible = ref(true)
const themes = [vueThemeLight, vueThemeDark]
const workspaces = [new KritzelWorkspace({ objects: createSeedObjects() })]

function setZoomPanelVisible(event: Event) {
  isZoomPanelVisible.value = (event.target as HTMLInputElement).checked
}
</script>

<template>
  <div :style="hostStyle">
    <div :style="toolbarStyle">
      <label class="checkbox-control">
        <input type="checkbox" :checked="isZoomPanelVisible" @change="setZoomPanelVisible" />
        <span>Zoom panel</span>
      </label>
    </div>
    <KritzelEditor
      editorId="zoom-panel-toggle"
      theme="light"
      :themes="themes"
      :workspaces="workspaces"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isZoomPanelVisible="isZoomPanelVisible"
      :style="editorStyle"
    />
  </div>
</template>

<style scoped>
.checkbox-control {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  color: #333;
  font-size: 13px;
  cursor: pointer;
}
</style>
