// demos/vue/src/pages/advanced/user-management/UserManagementLoginPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import {
  getEditorRef,
  KritzelEditor,
  KritzelWorkspace,
  type IKritzelUser,
  type KritzelLoginConfig,
  type LoginEvent,
} from '@kritzel/vue-editor'
import { vueThemeDark } from '../../../const/vue-theme-dark'
import { vueThemeLight } from '../../../const/vue-theme-light'
import { createSeedObjects } from '../../getting-started/seed-objects'

const editor = getEditorRef('editor')
const themes = [vueThemeLight, vueThemeDark]
const workspaces = [new KritzelWorkspace({ objects: createSeedObjects() })]
const user = ref<IKritzelUser>()
const loginConfig: KritzelLoginConfig = {
  title: 'Sign in',
  providers: [
    { name: 'google', icon: 'google', label: 'Continue with Google' },
    { name: 'facebook', icon: 'facebook', label: 'Continue with Facebook' },
    { name: 'github', icon: 'github', label: 'Continue with GitHub' },
  ],
}

async function onReady(): Promise<void> {
  await editor.value?.openLoginDialog()
}

async function onLogin(event: CustomEvent<LoginEvent>): Promise<void> {
  const provider = event.detail.provider
  user.value = {
    id: `user-${provider}-1`,
    displayName: 'Ada Lovelace',
    color: '#42b883',
    isGuest: false,
  }
  await editor.value?.closeLoginDialog()
}

function onLogout(): void {
  user.value = undefined
}
</script>

<template>
  <KritzelEditor
    ref="editor"
    editorId="user-management-login"
    :loginConfig="loginConfig"
    :user="user"
    :workspaces="workspaces"
    theme="light"
    :themes="themes"
    :isPanningEnabled="false"
    :isZoomingEnabled="false"
    :isMoreMenuVisible="false"
    :isWorkspaceManagerVisible="false"
    @isReady="onReady"
    @login="onLogin"
    @logout="onLogout"
    style="display: block; width: 100%; height: 100vh"
  />
</template>

// demos/react/src/pages/advanced/user-management/UserManagementLoginPage.tsx
import { useMemo, useRef, useState } from "react";
import { KritzelEditor, type HTMLKritzelEditorElement, type IKritzelUser } from "@kritzel/react-editor";
import { reactThemeDark } from "../../../const/react-theme-dark";
import { reactThemeLight } from "../../../const/react-theme-light";
import { createAuthenticatedUser, createUserManagementWorkspaces, loginConfig } from "./user-management-shared";

export function UserManagementLoginPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const [user, setUser] = useState<IKritzelUser>();
  const workspaces = useMemo(() => createUserManagementWorkspaces(), []);

  return (
    <KritzelEditor
      ref={editorRef}
      editorId="user-management-login"
      loginConfig={loginConfig}
      user={user}
      workspaces={workspaces}
      theme="light"
      themes={[reactThemeLight, reactThemeDark]}
      isPanningEnabled={false}
      isZoomingEnabled={false}
      isMoreMenuVisible={false}
      isWorkspaceManagerVisible={false}
      onIsReady={() => void editorRef.current?.openLoginDialog()}
      onLogin={(event) => {
        setUser(createAuthenticatedUser(event.detail.provider));
        void editorRef.current?.closeLoginDialog();
      }}
      onLogout={() => setUser(undefined)}
      style={{ display: "block", width: "100%", height: "100%" }}
    />
  );
}
