// demos/vue/src/pages/advanced/collaboration/CollaborationLocalPage.vue
<script setup lang="ts">
import {
  BroadcastSyncProvider,
  KritzelEditor,
  KritzelWorkspace,
  type KritzelSyncConfig,
} from '@kritzel/vue-editor'
import { vueThemeDark } from '../../../const/vue-theme-dark'
import { vueThemeLight } from '../../../const/vue-theme-light'
import { createSeedObjects } from '../../getting-started/seed-objects'
import { editorStyle, hostStyle } from '../../shared/demo-shared'
import Toolbar from '../../../components/Toolbar.vue'

const themes = [vueThemeLight, vueThemeDark]
const workspaces = [new KritzelWorkspace({ objects: createSeedObjects() })]
const syncConfig: KritzelSyncConfig = {
  providers: [BroadcastSyncProvider],
}
</script>

<template>
  <div :style="{ ...hostStyle, background: 'linear-gradient(160deg, #e8fbf3 0%, #ffffff 46%)' }">
    <Toolbar>
      <span class="label">Cross-tab Sync</span>
      <span class="status">BroadcastChannel enabled</span>
    </Toolbar>
    <KritzelEditor
      editorId="collaboration-local"
      theme="light"
      :themes="themes"
      :workspaces="workspaces"
      :syncConfig="syncConfig"
      :loginConfig="undefined"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isMoreMenuVisible="false"
      :isWorkspaceManagerVisible="false"
      :style="editorStyle"
    />
  </div>
</template>

// demos/react/src/pages/advanced/collaboration/CollaborationLocalPage.tsx
import { useMemo } from "react";
import {
  BroadcastSyncProvider,
  KritzelEditor,
  type KritzelSyncConfig,
  KritzelWorkspace,
} from "@kritzel/react-editor";
import { reactThemeLight } from "../../../const/react-theme-light";
import { reactThemeDark } from "../../../const/react-theme-dark";
import { createSeedObjects } from "../../getting-started/seed-objects";
import {
  editorStyle,
  hostStyle,
} from "../../shared/demo-shared";
import { Toolbar } from "../../../components/Toolbar";

export function CollaborationLocalPage() {
  const syncConfig = useMemo<KritzelSyncConfig>(
    () => ({ providers: [BroadcastSyncProvider] }),
    [],
  );
  const workspaces = useMemo(
    () => [new KritzelWorkspace({ objects: createSeedObjects() })],
    [],
  );

  return (
    <div style={{ ...hostStyle, background: "linear-gradient(160deg, #e9f8ff 0%, #ffffff 46%)" }}>
      <Toolbar>
        <span className="label">Cross-tab Sync</span>
        <span className="status">BroadcastChannel enabled</span>
      </Toolbar>
      <KritzelEditor
        editorId="collaboration-local"
        syncConfig={syncConfig}
        theme="light"
        themes={[reactThemeLight, reactThemeDark]}
        workspaces={workspaces}
        loginConfig={undefined}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        style={editorStyle}
      />
    </div>
  );
}
