// demos/react/src/pages/advanced/import-export/ImportExportViewportExportPage.tsx
import { useMemo, useRef } from "react";
import { KritzelEditor, KritzelWorkspace, type HTMLKritzelEditorElement } from "@kritzel/react-editor";
import { reactThemeLight } from "../../../const/react-theme-light";
import { reactThemeDark } from "../../../const/react-theme-dark";
import { createSeedObjects } from "../../getting-started/seed-objects";
import { Toolbar } from "../../../components/Toolbar";

export function ImportExportViewportExportPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const workspaces = useMemo(
    () => [new KritzelWorkspace({ objects: createSeedObjects() })],
    [],
  );

  async function exportAsPng() {
    await editorRef.current?.exportViewportAsPng();
  }

  async function exportAsSvg() {
    await editorRef.current?.exportViewportAsSvg();
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100%", fontFamily: "sans-serif" }}>
      <Toolbar>
        <span className="label">Viewport Export</span>
        <button onClick={() => void exportAsPng()}>Export as PNG</button>
        <button onClick={() => void exportAsSvg()}>Export as SVG</button>
      </Toolbar>
      <KritzelEditor
        ref={editorRef}
        editorId="import-export-viewport-export"
        theme="light"
        themes={[reactThemeLight, reactThemeDark]}
        workspaces={workspaces}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        style={{ flex: 1, minHeight: 0 }}
      />
    </div>
  );
}

// demos/vue/src/pages/advanced/import-export/ImportExportViewportExportPage.vue
<script setup lang="ts">
import { getEditorRef, KritzelEditor, KritzelWorkspace } from '@kritzel/vue-editor'
import { vueThemeDark } from '../../../const/vue-theme-dark'
import { vueThemeLight } from '../../../const/vue-theme-light'
import { createSeedObjects } from '../../getting-started/seed-objects'
import Toolbar from '../../../components/Toolbar.vue'

const editor = getEditorRef('editor')
const themes = [vueThemeLight, vueThemeDark]
const workspaces = [new KritzelWorkspace({ objects: createSeedObjects() })]

async function exportAsPng(): Promise<void> {
  await editor.value?.exportViewportAsPng()
}

async function exportAsSvg(): Promise<void> {
  await editor.value?.exportViewportAsSvg()
}
</script>

<template>
  <div class="page">
    <Toolbar>
      <button type="button" @click="exportAsPng">Export as PNG</button>
      <button type="button" @click="exportAsSvg">Export as SVG</button>
    </Toolbar>
    <div class="editor-wrap">
      <KritzelEditor
        ref="editor"
        editorId="import-export-viewport-export"
        theme="light"
        :themes="themes"
        :workspaces="workspaces"
        :isPanningEnabled="false"
        :isZoomingEnabled="false"
        :isMoreMenuVisible="false"
        :isWorkspaceManagerVisible="false"
      />
    </div>
  </div>
</template>

<style scoped>
.page { display: flex; flex-direction: column; height: 100vh; font-family: sans-serif; }
.editor-wrap { flex: 1; position: relative; min-height: 0; }
.editor-wrap > * { display: block; height: 100%; }
</style>
