// apps/demos/vue/src/pages/advanced/dynamic-objects/DynamicObjectsComponentPage.vue
<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue'
import {
  getEditorRef,
  KritzelDynamicObject,
  KritzelEditor,
  registerVueDynamicObjectRenderer,
  type HTMLKritzelEditorElement,
} from '@kritzel/vue-editor'
import { vueThemeLight } from '../../../const/vue-theme-light'
import CounterWidget from './CounterWidget.ce.vue'

type CounterWidgetState = {
  count: number
}

function createCounterWidgetInitialState(): CounterWidgetState {
  return { count: 0 }
}

const COUNTER_RENDERER_KEY = 'vue-dynamic-object-counter'

const editor = getEditorRef('editor')
const hasAddedInitialDynamicObject = ref(false)
const unregisterCounterRenderer = registerVueDynamicObjectRenderer(COUNTER_RENDERER_KEY, {
  tagName: '@kritzel/vue-editor-counter-widget',
  component: CounterWidget,
  createInitialState: createCounterWidgetInitialState,
})

onBeforeUnmount(() => {
  unregisterCounterRenderer()
})

async function onReady() {
  const editorValue = editor.value as HTMLKritzelEditorElement | undefined
  if (!editorValue || hasAddedInitialDynamicObject.value) {
    return
  }

  const objectCount = await editorValue.getObjectsTotalCount()
  if (objectCount > 0) {
    return
  }

  hasAddedInitialDynamicObject.value = true

  const placeholder = document.createElement('div')
  placeholder.textContent = 'Loading Counter...'

  const dynamicObject = new KritzelDynamicObject({
    element: placeholder,
    rendererKey: COUNTER_RENDERER_KEY,
    rendererData: createCounterWidgetInitialState(),
    translateX: -150,
    translateY: -90,
    width: 260,
    height: 160,
  })

  dynamicObject.isRotatable = false

  await editorValue.addObject(dynamicObject)
}
</script>

<template>
  <div class="page">
    <div class="toolbar">
      <strong>Registered Component:</strong>
      <span>The object mounts a real Vue component via the renderer registry.</span>
    </div>
    <KritzelEditor
      ref="editor"
      editorId="dynamic-objects-component"
      theme="light"
      :themes="[vueThemeLight]"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isMoreMenuVisible="false"
      :isWorkspaceManagerVisible="false"
      @isReady="onReady"
    />
  </div>
</template>

<style scoped>
.page { display: flex; flex-direction: column; height: 100vh; }
.toolbar { display: flex; align-items: center; gap: 8px; padding: 8px 12px; background: #f5f5f5; border-bottom: 1px solid #ebebeb; font: 13px sans-serif; }
.toolbar strong { color: #42b883; }
KritzelEditor { flex: 1; min-height: 0; }
</style>

// demos/react/src/pages/advanced/dynamic-objects/DynamicObjectsComponentPage.tsx
import { useEffect, useRef } from "react";
import { createRoot, type Root } from "react-dom/client";
import {
  KritzelDynamicObject,
  KritzelEditor,
  type HTMLKritzelEditorElement,
} from "@kritzel/react-editor";
import { KritzelDynamicObjectRendererRegistry } from "@kritzel/react-editor";
import { reactThemeLight } from "../../../const/react-theme-light";
import { CounterWidget, createCounterWidgetInitialState, type CounterWidgetState } from "./CounterWidget";

const COUNTER_RENDERER_KEY = "react-dynamic-object-counter";

type MountedCounterRenderer = {
  root: Root;
  latestState: CounterWidgetState;
};

export function DynamicObjectsComponentPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const hasAddedInitialDynamicObject = useRef(false);
  const mountedRenderers = useRef<Map<string, MountedCounterRenderer>>(new Map());

  useEffect(() => {
    KritzelDynamicObjectRendererRegistry.register(COUNTER_RENDERER_KEY, {
      onMount: ({ object, container, data }) => {
        if (!container) {
          return;
        }

        const initialState = (data as CounterWidgetState | undefined) ?? createCounterWidgetInitialState();

        const root = createRoot(container);
        const renderer: MountedCounterRenderer = { root, latestState: initialState };
        mountedRenderers.current.set(object.id, renderer);

        root.render(
          <CounterWidget
            initialState={initialState}
            onStateChange={(nextState) => {
              const current = mountedRenderers.current.get(object.id);
              if (current) {
                current.latestState = nextState;
              }
            }}
          />,
        );
      },
      onUnmount: ({ object, container }) => {
        const renderer = mountedRenderers.current.get(object.id);
        if (!renderer) {
          return undefined;
        }

        const snapshot = renderer.latestState;
        renderer.root.unmount();
        mountedRenderers.current.delete(object.id);

        if (container) {
          container.innerHTML = "";
        }

        return snapshot;
      },
    });

    return () => {
      mountedRenderers.current.forEach((renderer) => {
        renderer.root.unmount();
      });
      mountedRenderers.current.clear();
      KritzelDynamicObjectRendererRegistry.unregister(COUNTER_RENDERER_KEY);
    };
  }, []);

  async function onReady() {
    if (hasAddedInitialDynamicObject.current) {
      return;
    }

    const objectCount = await editorRef.current?.getObjectsTotalCount();
    if ((objectCount ?? 0) > 0) {
      return;
    }

    hasAddedInitialDynamicObject.current = true;

    const placeholder = document.createElement("div");
    placeholder.textContent = "Loading Counter...";

    const dynamicObject = new KritzelDynamicObject({
      element: placeholder,
      rendererKey: COUNTER_RENDERER_KEY,
      rendererData: createCounterWidgetInitialState(),
      translateX: -150,
      translateY: -90,
      width: 260,
      height: 160,
    });

    dynamicObject.isRotatable = false;

    await editorRef.current?.addObject(dynamicObject);
  }

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100vh", fontFamily: "sans-serif" }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, padding: 8, background: "#f5f5f5", borderBottom: "1px solid #ddd" }}>
        <strong>Registered Component:</strong>
        <span>The object mounts a real React component via the renderer registry.</span>
      </div>
      <KritzelEditor
        ref={editorRef}
        editorId="dynamic-objects-component"
        theme="light"
        themes={[reactThemeLight]}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        onIsReady={() => {
          void onReady();
        }}
        style={{ flex: 1, minHeight: 0 }}
      />
    </div>
  );
}
