// demos/vue/src/pages/advanced/dynamic-objects/DynamicObjectsIframePage.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'
import { KritzelEditor, KritzelIframeObject, KritzelWorkspace } from '@kritzel/vue-editor'
import { vueThemeDark } from '../../../const/vue-theme-dark'
import { vueThemeLight } from '../../../const/vue-theme-light'
import { mockChatPrompts, mockComponentDefinitions } from './iframe-calculator-definitions'

function createRuntimeObject(): KritzelIframeObject {
  const definition = mockComponentDefinitions[0]
  const object = new KritzelIframeObject({
    content: definition.content,
    loadingContent: definition.loadingContent,
    state: definition.initialState,
    title: definition.name,
    translateX: -140,
    translateY: -200,
    width: 280,
    height: 320,
    borderRadius: 12,
    boxShadow: '0 12px 32px rgba(32, 33, 36, 0.12)',
  })
  object.isRotatable = false
  return object
}

const runtimeObject = createRuntimeObject()
const themes = [vueThemeLight, vueThemeDark]
const workspaces = [new KritzelWorkspace({ objects: [runtimeObject] })]
const promptIndex = ref(0)
const promptText = ref(mockChatPrompts[0])
const queryLabel = computed(() => `${promptIndex.value + 1} of ${mockChatPrompts.length}`)
let responseTimeout: ReturnType<typeof setTimeout> | undefined

function showPrompt(offset: -1 | 1): void {
  const nextIndex = Math.max(0, Math.min(promptIndex.value + offset, mockChatPrompts.length - 1))
  if (nextIndex === promptIndex.value) {
    return
  }

  if (responseTimeout) {
    clearTimeout(responseTimeout)
  }
  promptIndex.value = nextIndex
  promptText.value = mockChatPrompts[nextIndex]
  const definition = mockComponentDefinitions[nextIndex]
  runtimeObject.setLoadingContent(definition.loadingContent)
  runtimeObject.setContent(definition.loadingContent)
  runtimeObject.setLoading(true)
  responseTimeout = setTimeout(() => {
    runtimeObject.setState(definition.initialState)
    runtimeObject.setContent(definition.content)
    runtimeObject.setLoading(false)
    responseTimeout = undefined
  }, 1100)
}

onBeforeUnmount(() => {
  if (responseTimeout) {
    clearTimeout(responseTimeout)
  }
})
</script>

<template>
  <div class="page">
    <KritzelEditor
      editorId="dynamic-objects-iframe"
      theme="light"
      :themes="themes"
      :workspaces="workspaces"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isToolbarVisible="false"
      :isMoreMenuVisible="false"
      :isWorkspaceManagerVisible="false"
    />
    <div class="chat-input">
      <textarea v-model="promptText" rows="3" aria-label="Mock LLM prompt"></textarea>
      <div class="query-nav" aria-label="Mock prompt navigation">
        <button type="button" aria-label="Previous query" :disabled="promptIndex === 0" @click="showPrompt(-1)">&lt;</button>
        <span>{{ queryLabel }}</span>
        <button type="button" aria-label="Next query" :disabled="promptIndex === mockChatPrompts.length - 1" @click="showPrompt(1)">&gt;</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.page { position: relative; height: 100vh; }
.page > :first-child { display: block; width: 100%; height: 100%; }
.chat-input { position: absolute; left: 50%; bottom: 18px; z-index: 20; width: min(460px, calc(100% - 32px)); padding: 10px; border: 1px solid #e5e7eb; border-radius: 16px; background: #ffffff; box-shadow: 0 16px 42px rgba(32, 33, 36, 0.18); box-sizing: border-box; transform: translateX(-50%); font-family: Roboto, sans-serif; }
textarea { display: block; width: 100%; height: 98px; resize: none; border: 0; border-radius: 12px; padding: 12px 14px 38px; box-sizing: border-box; background: #f3f4f6; font: inherit; line-height: 1.45; }
.query-nav { position: absolute; right: 18px; bottom: 18px; display: flex; align-items: center; gap: 6px; color: #5f6368; font-size: 12px; font-weight: 700; }
.query-nav button { width: 26px; height: 26px; border: 0; border-radius: 50%; padding: 0; background: #ffffff; cursor: pointer; font-size: 18px; }
.query-nav button:disabled { color: #b8bdc4; cursor: default; opacity: 0.55; }
</style>

// demos/react/src/pages/advanced/dynamic-objects/DynamicObjectsIframePage.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { KritzelEditor, KritzelIframeObject, KritzelWorkspace } from "@kritzel/react-editor";
import { reactThemeDark } from "../../../const/react-theme-dark";
import { reactThemeLight } from "../../../const/react-theme-light";
import { mockChatPrompts, mockComponentDefinitions } from "./iframe-calculator-definitions";

function createRuntimeObject(): KritzelIframeObject {
  const definition = mockComponentDefinitions[0];
  const object = new KritzelIframeObject({
    content: definition.content,
    loadingContent: definition.loadingContent,
    state: definition.initialState,
    title: definition.name,
    translateX: -140,
    translateY: -200,
    width: 280,
    height: 320,
    borderRadius: 12,
    boxShadow: "0 12px 32px rgba(32, 33, 36, 0.12)",
  });
  object.isRotatable = false;
  return object;
}

export function DynamicObjectsIframePage() {
  const runtimeObject = useMemo(() => createRuntimeObject(), []);
  const workspaces = useMemo(() => [new KritzelWorkspace({ objects: [runtimeObject] })], [runtimeObject]);
  const [promptIndex, setPromptIndex] = useState(0);
  const [promptText, setPromptText] = useState(mockChatPrompts[0]);
  const responseTimeout = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => () => {
    if (responseTimeout.current) clearTimeout(responseTimeout.current);
  }, []);

  function showPrompt(offset: -1 | 1) {
    const nextIndex = Math.max(0, Math.min(promptIndex + offset, mockChatPrompts.length - 1));
    if (nextIndex === promptIndex) return;

    if (responseTimeout.current) clearTimeout(responseTimeout.current);
    setPromptIndex(nextIndex);
    setPromptText(mockChatPrompts[nextIndex]);
    const definition = mockComponentDefinitions[nextIndex];
    runtimeObject.setLoadingContent(definition.loadingContent);
    runtimeObject.setContent(definition.loadingContent);
    runtimeObject.setLoading(true);
    responseTimeout.current = setTimeout(() => {
      runtimeObject.setState(definition.initialState);
      runtimeObject.setContent(definition.content);
      runtimeObject.setLoading(false);
      responseTimeout.current = null;
    }, 1100);
  }

  return (
    <div style={{ position: "relative", height: "100%" }}>
      <KritzelEditor
        editorId="dynamic-objects-iframe"
        theme="light"
        themes={[reactThemeLight, reactThemeDark]}
        workspaces={workspaces}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isToolbarVisible={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        style={{ display: "block", width: "100%", height: "100%" }}
      />
      <div style={{ position: "absolute", left: "50%", bottom: 18, zIndex: 20, width: "min(460px, calc(100% - 32px))", padding: 10, border: "1px solid #e5e7eb", borderRadius: 16, background: "#fff", boxShadow: "0 16px 42px rgba(32,33,36,.18)", boxSizing: "border-box", transform: "translateX(-50%)", fontFamily: "Roboto, sans-serif" }}>
        <textarea rows={3} aria-label="Mock LLM prompt" value={promptText} onChange={(event) => setPromptText(event.target.value)} style={{ display: "block", width: "100%", height: 98, resize: "none", border: 0, borderRadius: 12, padding: "12px 14px 38px", boxSizing: "border-box", background: "#f3f4f6", font: "inherit", lineHeight: 1.45 }} />
        <div aria-label="Mock prompt navigation" style={{ position: "absolute", right: 18, bottom: 18, display: "flex", alignItems: "center", gap: 6, color: "#5f6368", fontSize: 12, fontWeight: 700 }}>
          <button type="button" aria-label="Previous query" disabled={promptIndex === 0} onClick={() => showPrompt(-1)}>‹</button>
          <span>{promptIndex + 1} of {mockChatPrompts.length}</span>
          <button type="button" aria-label="Next query" disabled={promptIndex === mockChatPrompts.length - 1} onClick={() => showPrompt(1)}>›</button>
        </div>
      </div>
    </div>
  );
}
