// demos/vue/src/pages/customization/theming/ThemingApplyPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import { KritzelEditor, KritzelWorkspace } from '@kritzel/vue-editor'
import { vueThemeDark } from '../../../const/vue-theme-dark'
import { vueThemeLight } from '../../../const/vue-theme-light'
import { createSeedObjects } from '../../getting-started/seed-objects'
import { editorStyle, hostStyle } from '../../shared/demo-shared'
import Toolbar from '../../../components/Toolbar.vue'

const themes = [vueThemeLight, vueThemeDark]
const workspaces = [new KritzelWorkspace({ objects: createSeedObjects() })]
const activeTheme = ref('light')
</script>

<template>
  <div :style="hostStyle">
    <Toolbar>
      <button :class="{ active: activeTheme === 'light' }" @click="activeTheme = 'light'">Light</button>
      <button :class="{ active: activeTheme === 'dark' }" @click="activeTheme = 'dark'">Dark</button>
    </Toolbar>
    <KritzelEditor
      editorId="theming-apply"
      :theme="activeTheme"
      :themes="themes"
      :workspaces="workspaces"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isMoreMenuVisible="true"
      :isWorkspaceManagerVisible="true"
      :style="editorStyle"
    />
  </div>
</template>

// demos/react/src/pages/customization/theming/ThemingApplyPage.tsx
import { useRef, useState } from "react";
import {
  KritzelEditor,
  HTMLKritzelEditorElement,
} from "@kritzel/react-editor";
import { reactThemeLight } from "../../../const/react-theme-light";
import { reactThemeDark } from "../../../const/react-theme-dark";
import {
  editorStyle,
  hostStyle,
  seedEditor,
} from "../../shared/demo-shared";
import { Toolbar } from "../../../components/Toolbar";

const themes = [reactThemeLight, reactThemeDark];

export function ThemingApplyPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const [activeName, setActiveName] = useState("light");

  return (
    <div style={hostStyle}>
      <Toolbar>
        <button className={activeName === "light" ? "active" : undefined} onClick={() => setActiveName("light")}>Light</button>
        <button className={activeName === "dark" ? "active" : undefined} onClick={() => setActiveName("dark")}>Dark</button>
      </Toolbar>
      <KritzelEditor
        ref={editorRef}
        editorId="theming-apply"
        theme={activeName}
        themes={themes}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={true}
        isWorkspaceManagerVisible={true}
        onIsReady={() => {
          if (editorRef.current) {
            void seedEditor(editorRef.current);
          }
        }}
        style={editorStyle}
      />
    </div>
  );
}
