// demos/react/src/pages/customization/localization/LocalizationSwitchPage.tsx
import { useRef, useState } from "react";
import { KritzelEditor, type HTMLKritzelEditorElement } from "@kritzel/react-editor";
import { reactThemeLight } from "../../../const/react-theme-light";

export function LocalizationSwitchPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const [locale, setLocale] = useState("en");

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "100vh", fontFamily: "sans-serif" }}>
      <div style={{ display: "flex", gap: 8, padding: 8, background: "#f5f5f5", borderBottom: "1px solid #ddd" }}>
        <strong>Locale:</strong>
        {[["en", "English"], ["de", "German"], ["fr", "French"]].map(([code, label]) => (
          <button key={code} onClick={() => setLocale(code)}>{label} ({code})</button>
        ))}
      </div>
      <KritzelEditor
        ref={editorRef}
        editorId="localization-switch"
        locale={locale}
        theme="light"
        themes={[reactThemeLight]}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible
        isWorkspaceManagerVisible
        onLocaleChange={(event) => setLocale(event.detail)}
        style={{ flex: 1, minHeight: 0 }}
      />
      <div style={{ padding: 8, background: "#f5f5f5", fontFamily: "monospace" }}>Active Locale: {locale}</div>
    </div>
  );
}

// demos/vue/src/pages/customization/localization/LocalizationSwitchPage.vue
<script setup lang="ts">
import { ref } from 'vue'
import { KritzelEditor } from '@kritzel/vue-editor'
import { vueThemeLight } from '../../../const/vue-theme-light'

const locale = ref('en')
</script>

<template>
  <div class="page">
    <div class="toolbar">
      <strong>Locale:</strong>
      <button v-for="item in [['en', 'English'], ['de', 'German'], ['fr', 'French']]" :key="item[0]" @click="locale = item[0]">{{ item[1] }} ({{ item[0] }})</button>
    </div>
    <KritzelEditor editorId="localization-switch" :locale="locale" theme="light" :themes="[vueThemeLight]" :isPanningEnabled="false" :isZoomingEnabled="false" :isMoreMenuVisible="true" :isWorkspaceManagerVisible="true" @localeChange="locale = $event.detail" />
    <div class="status">Active Locale: {{ locale }}</div>
  </div>
</template>

<style scoped>
.page { display: flex; flex-direction: column; height: 100vh; font-family: sans-serif; }
.toolbar, .status { padding: 8px; background: #f5f5f5; border-bottom: 1px solid #ddd; display: flex; gap: 8px; }
.status { border-top: 1px solid #ddd; border-bottom: 0; font-family: monospace; }
KritzelEditor { flex: 1; min-height: 0; }
</style>
