// demos/react/src/pages/advanced/dynamic-objects/DynamicObjectsElementPage.tsx
import { useEffect, useRef } from "react";
import { createRoot, type Root } from "react-dom/client";
import {
  KritzelDynamicObject,
  KritzelEditor,
  type HTMLKritzelEditorElement,
} from "@kritzel/react-editor";
import { KritzelDynamicObjectRendererRegistry } from "@kritzel/react-editor";
import { reactThemeLight } from "../../../const/react-theme-light";
import { editorStyle, hostStyle } from "../../shared/demo-shared";
import {
  cloneTodoListState,
  createTodoListInitialState,
  TodoListComponent,
  type TodoListState,
} from "./TodoListComponent";

const TODO_RENDERER_KEY = "react-todo-list";

type MountedTodoRenderer = {
  root: Root;
  latestState: TodoListState;
};

export function DynamicObjectsElementPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);
  const hasAddedInitialDynamicObject = useRef(false);
  const mountedRenderers = useRef<Map<string, MountedTodoRenderer>>(new Map());

  useEffect(() => {
    KritzelDynamicObjectRendererRegistry.register(TODO_RENDERER_KEY, {
      onMount: ({ object, container, data }) => {
        if (!container) {
          return;
        }

        const initialState = cloneTodoListState(
          (data as TodoListState | undefined) ?? createTodoListInitialState(),
        );

        const root = createRoot(container);
        const renderer: MountedTodoRenderer = {
          root,
          latestState: initialState,
        };

        mountedRenderers.current.set(object.id, renderer);

        root.render(
          <TodoListComponent
            initialState={initialState}
            onStateChange={(nextState) => {
              const current = mountedRenderers.current.get(object.id);
              if (current) {
                current.latestState = cloneTodoListState(nextState);
              }
            }}
          />,
        );
      },
      onUnmount: ({ object, container }) => {
        const renderer = mountedRenderers.current.get(object.id);
        if (!renderer) {
          return undefined;
        }

        const snapshot = cloneTodoListState(renderer.latestState);
        renderer.root.unmount();
        mountedRenderers.current.delete(object.id);

        if (container) {
          container.innerHTML = "";
        }

        return snapshot;
      },
    });

    return () => {
      mountedRenderers.current.forEach((renderer) => {
        renderer.root.unmount();
      });
      mountedRenderers.current.clear();
      KritzelDynamicObjectRendererRegistry.unregister(TODO_RENDERER_KEY);
    };
  }, []);

  async function onReady() {
    if (hasAddedInitialDynamicObject.current) {
      return;
    }

    const objectCount = await editorRef.current?.getObjectsTotalCount();
    if ((objectCount ?? 0) > 0) {
      return;
    }

    hasAddedInitialDynamicObject.current = true;

    const placeholder = document.createElement("div");
    placeholder.textContent = "Loading Todo List...";

    const dynamicObject = new KritzelDynamicObject({
      element: placeholder,
      rendererKey: TODO_RENDERER_KEY,
      rendererData: createTodoListInitialState(),
      translateX: -300,
      translateY: -180,
      width: 600,
      height: 380,
    });

    dynamicObject.isRotatable = false;

    await editorRef.current?.addObject(dynamicObject);
  }

  return (
    <div style={hostStyle}>
      <KritzelEditor
        ref={editorRef}
        editorId="react-dynamic-objects"
        theme="light"
        themes={[reactThemeLight]}
        style={editorStyle}
        onIsReady={() => {
          void onReady();
        }}
      />
    </div>
  );
}

// demos/vue/src/pages/advanced/dynamic-objects/DynamicObjectsElementPage.vue
<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue'
import {
  getEditorRef,
  KritzelDynamicObject,
  KritzelEditor,
  registerVueDynamicObjectRenderer,
  type HTMLKritzelEditorElement,
} from '@kritzel/vue-editor'
import { vueThemeLight } from '../../../const/vue-theme-light.ts'
import { editorStyle, hostStyle } from '../../shared/demo-shared'
import TodoListCustomElement from './TodoListCustomElement.ce.vue'

type TodoItem = {
  id: number
  title: string
  isCompleted: boolean
}

type TodoListState = {
  todos: TodoItem[]
  nextId: number
}

const DEFAULT_TODO_STATE: TodoListState = {
  nextId: 4,
  todos: [
    { id: 1, title: 'Review project docs', isCompleted: true },
    { id: 2, title: 'Build a Vue custom element', isCompleted: false },
    { id: 3, title: 'Verify renderer rehydration', isCompleted: false },
  ],
}

function createTodoListInitialState(): TodoListState {
  return {
    nextId: DEFAULT_TODO_STATE.nextId,
    todos: DEFAULT_TODO_STATE.todos.map((todo) => ({ ...todo })),
  }
}

const TODO_RENDERER_KEY = 'vue-todo-list'

const editor = getEditorRef('customElementsEditor')
const hasAddedInitialDynamicObject = ref(false)
const unregisterTodoRenderer = registerVueDynamicObjectRenderer(TODO_RENDERER_KEY, {
  tagName: '@kritzel/vue-editor-todo-list',
  component: TodoListCustomElement,
  createInitialState: createTodoListInitialState,
})

onBeforeUnmount(() => {
  unregisterTodoRenderer()
})

async function onReady() {
  const editorValue = editor.value as HTMLKritzelEditorElement | undefined
  if (!editorValue || hasAddedInitialDynamicObject.value) {
    return
  }

  const objectCount = await editorValue.getObjectsTotalCount()
  if (objectCount > 0) {
    return
  }

  hasAddedInitialDynamicObject.value = true

  const placeholder = document.createElement('div')
  placeholder.textContent = 'Loading Todo List...'

  const dynamicObject = new KritzelDynamicObject({
    element: placeholder,
    rendererKey: TODO_RENDERER_KEY,
    rendererData: createTodoListInitialState(),
    translateX: -300,
    translateY: -180,
    width: 600,
    height: 380,
  })

  dynamicObject.isRotatable = false

  await editorValue.addObject(dynamicObject)
}
</script>

<template>
  <div :style="hostStyle">
    <KritzelEditor
      ref="customElementsEditor"
      editorId="vue-dynamic-objects"
      theme="light"
      :themes="[vueThemeLight]"
      :style="editorStyle"
      @isReady="onReady"
    />
  </div>
</template>
