// demos/react/src/pages/fundamentals/persistence/PersistenceLocalPage.tsx
import { useRef } from "react";
import {
  IndexedDBSyncProvider,
  KritzelEditor,
  type HTMLKritzelEditorElement,
  type KritzelSyncConfig,
} from "@kritzel/react-editor";
import { reactThemeDark } from "../../../const/react-theme-dark";
import { reactThemeLight } from "../../../const/react-theme-light";
import { createSeedObjects } from "../../getting-started/seed-objects";
import {
  editorStyle,
  hostStyle,
} from "../../shared/demo-shared";

const themes = [reactThemeLight, reactThemeDark];
const syncConfig: KritzelSyncConfig = {
  providers: [IndexedDBSyncProvider],
  appStateId: "persistence-local",
};

export function PersistenceLocalPage() {
  const editorRef = useRef<HTMLKritzelEditorElement | null>(null);

  async function onReady() {
    const editor = editorRef.current;
    if (!editor) return;

    const existing = await editor.getAllObjects();
    if (existing.length === 0) {
      await editor.addObjects(createSeedObjects());
    }
  }

  return (
    <div style={{ ...hostStyle, background: "linear-gradient(180deg, #f3fbff 0%, #ffffff 100%)" }}>
      <KritzelEditor
        ref={editorRef}
        editorId="persistence-local"
        syncConfig={syncConfig}
        theme="light"
        themes={themes}
        loginConfig={undefined}
        isPanningEnabled={false}
        isZoomingEnabled={false}
        isMoreMenuVisible={false}
        isWorkspaceManagerVisible={false}
        onIsReady={() => void onReady()}
        style={editorStyle}
      />
    </div>
  );
}

// demos/vue/src/pages/fundamentals/persistence/PersistenceLocalPage.vue
<script setup lang="ts">
import {
  getEditorRef,
  IndexedDBSyncProvider,
  KritzelEditor,
  type KritzelSyncConfig,
} from '@kritzel/vue-editor'
import { vueThemeDark } from '../../../const/vue-theme-dark'
import { vueThemeLight } from '../../../const/vue-theme-light'
import { createSeedObjects } from '../../getting-started/seed-objects'
import {
  editorStyle,
  hostStyle,
} from '../../shared/demo-shared'

const editor = getEditorRef('editor')
const themes = [vueThemeLight, vueThemeDark]

const syncConfig: KritzelSyncConfig = {
  providers: [IndexedDBSyncProvider],
  appStateId: 'persistence-local',
}

async function onReady() {
  const existing = await editor.value?.getAllObjects()
  if (!editor.value || !existing || existing.length > 0) {
    return
  }

  await editor.value.addObjects(createSeedObjects())
}
</script>

<template>
  <div
    :style="{
      ...hostStyle,
      color: '#333333',
      background: 'linear-gradient(180deg, #f3fbf8 0%, #ffffff 100%)',
    }"
  >
    <KritzelEditor
      ref="editor"
      editorId="persistence-local"
      theme="light"
      :themes="themes"
      :syncConfig="syncConfig"
      :loginConfig="undefined"
      :isPanningEnabled="false"
      :isZoomingEnabled="false"
      :isMoreMenuVisible="false"
      :isWorkspaceManagerVisible="false"
      :style="editorStyle"
      @isReady="onReady"
    />
  </div>
</template>
